stages:
  - build
  - test
  - deploy

image: maven:3.8.5-openjdk-17

default:
  artifacts:
    expire_in: 1 hour

before_script:
  - cd implementation/common 
  - mvn clean install
#  - mvn install:install file -Dfile=target/common-1.0-SNAPSHOT.jar -DgroupId=com.ase -DartifactId=common -Dversion=1.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
  - cd ../../

buildAPIGateway:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/api-gateway && mvn package -Dmaven.test.skip

buildAnalyticReport:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/analyticReport && mvn package -Dmaven.test.skip

buildAttendance:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/attendance && mvn package -Dmaven.test.skip

buildBookmarkService:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/bookmarkService && mvn package -Dmaven.test.skip

buildCalendar:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/calendar && mvn package -Dmaven.test.skip

buildCommon:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/common && mvn package -Dmaven.test.skip

buildEvent:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/event && mvn package -Dmaven.test.skip

buildFeedback:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/feedback && mvn package -Dmaven.test.skip

buildLogin:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/login && mvn package -Dmaven.test.skip

buildMaintenance:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/maintenance && mvn package -Dmaven.test.skip

buildNotification:
   stage: build
   tags:
     - ase-0203
   script:
     - cd implementation/notification
     - mvn clean package -Dmaven.test.skip

buildRecommender:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/recommender && mvn package -Dmaven.test.skip

buildSearchServiceEvents:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/searchServiceEvents && mvn package -Dmaven.test.skip

buildSendNotification:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/sendNotification && mvn package -Dmaven.test.skip

buildTagging:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/taggingService && mvn package -Dmaven.test.skip

testAPIGateway:
  stage: test
  image: maven:3.8.5-openjdk-17
  needs:
    - buildAPIGateway
  tags:
    - ase-0203
  script:
    - cd implementation/api-gateway && mvn package -Dmaven.test.skip
    - mvn test

testAnalyticReport:
  stage: test 
  image: maven:3.8.5-openjdk-17
  needs:
    - buildAnalyticReport
  tags:
    - ase-0203
  script:
    - cd implementation/analyticReport && mvn package -Dmaven.test.skip
    - mvn test

testAttendance:
  stage: test 
  needs:
    - buildAttendance 
  tags:
    - ase-0203
  script:
    - cd implementation/attendance && mvn package -Dmaven.test.skip
    - mvn test

testBookmarkService:
  stage: test 
  needs:
    - buildBookmarkService 
  tags:
    - ase-0203
  script:
    - cd implementation/bookmarkService && mvn package -Dmaven.test.skip
    - mvn test

testCalendar:
  stage: test 
  needs: 
    - buildCalendar
  tags:
    - ase-0203
  script:
    - cd implementation/calendar && mvn package -Dmaven.test.skip
    - mvn test

testCommon:
  stage: test 
  needs: 
    - buildCommon
  tags:
    - ase-0203
  script:
    - cd implementation/common && mvn package -Dmaven.test.skip
    - mvn test

testEvent:
  stage: test 
  needs:
    - buildEvent 
  tags:
    - ase-0203
  script:
    - cd implementation/event && mvn package -Dmaven.test.skip
    - mvn test

testFeedback:
  stage: test 
  needs: 
    - buildFeedback
  tags:
    - ase-0203
  script:
    - cd implementation/feedback && mvn package -Dmaven.test.skip
    - mvn test

testLogin:
  stage: test 
  needs: 
    - buildLogin
  tags:
    - ase-0203
  script:
    - cd implementation/login && mvn package -Dmaven.test.skip
    - mvn test

testMaintenance:
  stage: test 
  needs:
    - buildMaintenance 
  tags:
    - ase-0203
  script:
    - cd implementation/maintenance && mvn package -Dmaven.test.skip
    - mvn test

testNotification:
   stage: test 
   needs: 
     - buildNotification
   tags:
     - ase-0203
   script:
     - cd implementation/notification && mvn package -Dmaven.test.skip
     - mvn test

testRecommender:
  stage: test 
  needs: 
    - buildRecommender
  tags:
    - ase-0203
  script:
    - cd implementation/recommender && mvn package -Dmaven.test.skip
    - mvn test

testSearchServiceEvents:
  stage: test 
  needs: 
    - buildSearchServiceEvents
  tags:
    - ase-0203
  script:
    - cd implementation/searchServiceEvents && mvn package -Dmaven.test.skip
    - mvn test

testSendNotification:
  stage: test 
  needs: 
    - buildSendNotification
  tags:
    - ase-0203
  script:
    - cd implementation/sendNotification && mvn package -Dmaven.test.skip
    - mvn test

testTagging:
  stage: test 
  needs: 
    - buildTagging
  tags:
    - ase-0203
  script:
    - cd implementation/taggingService && mvn package -Dmaven.test.skip
    - mvn test


#deploy:
#  before_script:
#    - echo "deploy stage"
#  image:
#    name: docker
#
#  services:
#     - docker:dind
#
#  stage: deploy
#  tags:
#    - ase-0203
#  script:
#    - cd implementation
#    - docker compose up -d
