stages:
  - build
  - test

image: maven:3.8.5-openjdk-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  artifacts:
    expire_in: 7 days


buildBookmark:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/bookmarkService && mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - implementation/bookmarkService/target/

buildTagging:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/taggingService && mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - implementation/bookmarkService/target/  

testBookmark:
  stage: test
  dependencies:
    - buildBookmark
  script:
    - cd implementation/bookmarkService && mvn package -Dmaven.test.skip
    - mvn test
  tags:
      - ase-0203

testTagging:
  stage: test
  dependencies:
    - buildTagging
  script:
    - cd implementation/taggingService && mvn package -Dmaven.test.skip
    - mvn test
  tags:
      - ase-0203


