stages:
  - build
  - test

image: maven:3.8.5-openjdk-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  artifacts:
    expire_in: 7 days


build:
  stage: build
  tags:
    - ase-0203
  script:
    - cd implementation/bookmarkService && mvn package
  artifacts:
    paths:
      - implementation/bookmarkService/target/

test:
  stage: test
  script:
    - cd implementation/bookmark && mvn test
  tags:
    - ase-0203
  needs:
    - build