x-common-variables: &common-variables
  DEBUG: "false"
  RABBITMQ-HOST: "rabbitmq"


services:
  analyticReport:
    image: analyticreport
    build: analyticReport
    networks:
      analyticReport-rabbit:
      analyticReport-apigateway:

  attendance:
    image: attendance
    build: attendance
    networks:
      attendance-rabbit:
      attendance-apigateway:

  bookmarkService:
    image: bookmarkservice
    build: bookmarkService
    networks:
      bookmarkService-calendar:
      bookmarkService-rabbit:

  calendar:
    image: calendar
    build: calendar
    networks:
      bookmarkService-calendar:

  event:
    image: event
    build: event
    networks:
      event-rabbit:
      event-apigateway:
    environment:
      <<: *common-variables
    volumes:
      - ./_persistence/event:/persistence


  feedback:
    image: feedback
    build: feedback
    networks:
      feedback-rabbit:
      feedback-apigateway:

  login:
    image: login
    build: login
    networks:
      login-rabbit:
      login-apigateway:
    environment:
      <<: *common-variables
      JWT-SECRET: "top-secret"
      JWT-EXPIRATION-TIME: "900000"
    volumes:
      - ./_persistence/login:/persistence

  maintenance:
    image: maintenance
    build: maintenance
    networks:
      maintenance-rabbit:
      maintenance-apigateway:

  notification:
    image: notification
    build: notification
    networks:
      notification-rabbit:
      notification-apigateway:

  recommender:
    image: recommender
    build: recommender
    networks:
      recommender-rabbit:
      recommender-apigateway:

  searchServiceEvents:
    image: searchserviceevents
    build: searchServiceEvents
    networks:
      searchServiceEvent-rabbit:
      searchServiceEvent-apigateway:
    environment:
      <<: *common-variables
    volumes:
      - ./_persistence/searchService:/persistence

  taggingService:
    image: taggingservice
    build: taggingService
    networks:
      taggingService-rabbit:

  sendNotification:
    image: sendnotification
    build: sendNotification
    networks:
      sendNotification-rabbit:
      sendNotification-apigateway:
    environment:
      <<: *common-variables
      NOTIFICATION_SENDER_EMAIL: <email>
      NOTIFICATION_SENDER_PASSWORD: <password>
    volumes:
      - ./_persistence/sendNotification:/persistence

  #frontend:
   # image: frontend
    #build: frontend/frontend
    #networks:
     # frontend-apigateway:
    #ports:
     # - 4200:4200

  apigateway:
    image: api-gateway
    build: api-gateway
    environment:
      <<: *common-variables
      ANALYTIC_REPORT: analyticreport
      ATTENDANCE: attendance
      BOOKMARK_SERVICE: bookmarkservice
      CALENDAR: calendar
      EVENT: event
      FEEDBACK: feedback
      LOGIN: login
      MAINTENANCE: maintenance
      NOTIFICATION: notification
      RECOMMENDER: recommender
      SERCH_SERVICE_EVENTS: searchserviceevents
      TAGGING_SERVICE: taggingservice
    ports:
      - 8080:8080

    networks:
      analyticReport-apigateway:
      attendance-apigateway:
      event-apigateway:
      feedback-apigateway:
      login-apigateway:
      maintenance-apigateway:
      notification-apigateway:
      recommender-apigateway:
      searchServiceEvent-apigateway:
      sendNotification-apigateway:
      frontend-apigateway:

  rabbitmq:
    image: rabbitmq
    networks:
      analyticReport-rabbit:
      attendance-rabbit:
      bookmarkService-rabbit:
      event-rabbit:
      feedback-rabbit:
      login-rabbit:
      maintenance-rabbit:
      notification-rabbit:
      recommender-rabbit:
      searchServiceEvent-rabbit:
      sendNotification-rabbit:

networks:
  analyticReport-rabbit:
  attendance-rabbit:
  bookmarkService-rabbit:
  event-rabbit:
  feedback-rabbit:
  login-rabbit:
  maintenance-rabbit:
  notification-rabbit:
  recommender-rabbit:
  searchServiceEvent-rabbit:
  sendNotification-rabbit:
  taggingService-rabbit:

  bookmarkService-calendar:

  analyticReport-apigateway:
  attendance-apigateway:
  event-apigateway:
  feedback-apigateway:
  login-apigateway:
  maintenance-apigateway:
  notification-apigateway:
  recommender-apigateway:
  searchServiceEvent-apigateway:
  sendNotification-apigateway:
  frontend-apigateway:
