debug: ${DEBUG:true}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - UPDATE
              - DELETE


config:
  user-token-endpoint: http://${LOGIN:localhost}:8080/api/v1/login/getByToken
  endpoints:
    login:
      endpoint: http://${LOGIN:localhost}:8080
      path-base: /api/v1/login
      paths:
        -
        - /login
        - /register
      authorize: false
      gateway-path-base: /api/v1/login
server:
  port: 8080
