debug: ${DEBUG:true}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - UPDATE
              - DELETE


config:
  user-token-endpoint: http://${LOGIN:localhost}:8080/api/v1/login/getByToken
  endpoints:
    login:
      endpoint: http://${LOGIN:localhost}:8080
      path-base: /api/v1/login
      paths:
        -
        - /login
        - /register
      authorize: false
      gateway-path-base: /api/v1/login
    calendar:
      endpoint: http://${CALENDAR:localhost}:8080
      path-base: /api/v1/calendar
      paths:
        - /export
      gateway-path-base: /api/v1/calendar
    bookmark:
      endpoint: http://${BOOKMARK_SERVICE:localhost}:8080
      path-base: /api/v1/bookmark
      paths:
        - /add
        - /unbookmarkEvent
        - /bookmarkedEvents
        - /bookmarkedEventIds
      gateway-path-base: /api/v1/bookmark
    tagging:
      endpoint: http://${TAGGING_SERVICE:localhost}:8080
      path-base: /api/v1/tag
      paths:
        - /add
        - /event
        - /removeTag
        - /removeEvent
      gateway-path-base: /api/v1/tag
    event:
      endpoint: http://${EVENT:localhost}:8080
      path-base: /api/v1/events
      paths:
        -
        - /healthcheck
      gateway-path-base: /api/v1/events
    searchservice:
      endpoint: http://${SERCH_SERVICE_EVENTS:localhost}:8080
      path-base: /api/v1/searchService
      paths:
        -
        - /healthcheck
        - /organizer
        - /event
        - /capacity
        - /eventName
        - /description
        - /date
      gateway-path-base: /api/v1/searchService
    

server:
  port: 8080
